steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Build the application
  - name: 'node:20'
    entrypoint: 'node'
    args: ['deploy-build.js']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/snowytop-safaris:$COMMIT_SHA', '.']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/snowytop-safaris:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'snowytop-safaris'
    - '--image'
    - 'gcr.io/$PROJECT_ID/snowytop-safaris:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'

images:
  - 'gcr.io/$PROJECT_ID/snowytop-safaris:$COMMIT_SHA'